apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-apache2
  name: my-apache2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-apache2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-apache2
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
